# frozen_string_literal: true

module Templates
  module MDX
    # @see Templates::MDX::BuildAnchor
    class AnchorBuilder < ::Templates::MDX::AbstractBuilder
      # Standard security practice for arbitrary URLs.
      DEFAULT_REL = "noopener noreferrer nofollow"

      # Arbitrary anchor tags generated by this should open in a new window.
      DEFAULT_TARGET = "_blank"

      tag_name ?a

      option :href, Templates::Types::String

      option :label, Templates::Types::String

      option :title, Templates::Types::String.optional, optional: true

      option :rel, Templates::Types::String.optional, default: proc { DEFAULT_REL }

      option :target, Templates::Types::String.optional, default: proc { DEFAULT_TARGET }

      def build_attributes
        {
          href:,
          title:,
          target:,
          rel:,
        }.compact_blank
      end

      def build_inner_html
        label.strip
      end
    end
  end
end
