# frozen_string_literal: true

class CreateTemplatesInstanceDigests < ActiveRecord::Migration[7.0]
  def change
    create_table :templates_instance_digests, id: :uuid do |t|
      t.references :template_instance, type: :uuid, polymorphic: true, null: false, index: { unique: true, name: "idx_templates_instance_digests_uniqueness" }
      t.references :template_definition, type: :uuid, polymorphic: true, null: false, index: { name: "idx_templates_instance_digests_template_definition" }
      t.references :layout_instance, type: :uuid, polymorphic: true, null: false, index: { name: "idx_templates_instance_digests_layout_instance" }
      t.references :layout_definition, type: :uuid, polymorphic: true, null: false, index: { name: "idx_templates_instance_digests_layout_definition" }
      t.references :entity, type: :uuid, polymorphic: true, null: false, index: { name: "idx_templates_instance_digest_entity" }

      t.bigint :position, null: false

      t.enum :layout_kind, null: false, enum_type: :layout_kind
      t.enum :template_kind, null: false, enum_type: :template_kind
      t.enum :width, null: true, enum_type: :template_width

      t.uuid :generation, null: false

      t.jsonb :config, null: false, default: {}
      t.jsonb :slots, null: false, default: {}

      t.numeric :render_duration
      t.timestamp :last_rendered_at

      t.timestamps null: false, default: -> { "CURRENT_TIMESTAMP" }

      t.index %i[template_kind render_duration], name: "idx_templates_instance_digests_rendering_by_template"
      t.index %i[last_rendered_at entity_type entity_id], name: "idx_templates_instance_digests_rendered_by_entity"
    end

    reversible do |dir|
      dir.up do
        say_with_time "Adding sibling index" do
          execute(<<~SQL)
          CREATE INDEX idx_templates_instance_digests_siblings ON templates_instance_digests (
            template_instance_type, template_instance_id, layout_instance_type, layout_instance_id, position
          ) INCLUDE (config, layout_kind, template_kind, width);
          SQL
        end

        say_with_time "Populating templates_instance_digests" do
          exec_update(<<~SQL)
          WITH digested_template_instances AS (
            SELECT "templates_hero_instances"."id" AS template_instance_id, 'Templates::HeroInstance' AS template_instance_type, "templates_hero_instances"."template_definition_id", 'Templates::HeroDefinition' AS template_definition_type, "templates_hero_instances"."layout_instance_id", 'Layouts::HeroInstance' AS layout_instance_type, "layouts_hero_instances"."layout_definition_id", 'Layouts::HeroDefinition' AS layout_definition_type, "templates_hero_instances"."entity_id", "templates_hero_instances"."entity_type", "templates_hero_instances"."position", "templates_hero_instances"."layout_kind", "templates_hero_instances"."template_kind", CAST(NULL AS template_width) AS width, "templates_hero_instances"."generation", "templates_hero_instances"."config", "templates_hero_instances"."slots" || jsonb_build_object('template_kind', "templates_hero_instances"."template_kind") AS slots, "templates_hero_instances"."render_duration", "templates_hero_instances"."last_rendered_at" FROM "templates_hero_instances" INNER JOIN "layouts_hero_instances" ON "layouts_hero_instances"."id" = "templates_hero_instances"."layout_instance_id" INNER JOIN "templates_hero_definitions" ON "templates_hero_definitions"."id" = "templates_hero_instances"."template_definition_id"
            UNION ALL
            SELECT "templates_list_item_instances"."id" AS template_instance_id, 'Templates::ListItemInstance' AS template_instance_type, "templates_list_item_instances"."template_definition_id", 'Templates::ListItemDefinition' AS template_definition_type, "templates_list_item_instances"."layout_instance_id", 'Layouts::ListItemInstance' AS layout_instance_type, "layouts_list_item_instances"."layout_definition_id", 'Layouts::ListItemDefinition' AS layout_definition_type, "templates_list_item_instances"."entity_id", "templates_list_item_instances"."entity_type", "templates_list_item_instances"."position", "templates_list_item_instances"."layout_kind", "templates_list_item_instances"."template_kind", CAST(NULL AS template_width) AS width, "templates_list_item_instances"."generation", "templates_list_item_instances"."config", "templates_list_item_instances"."slots" || jsonb_build_object('template_kind', "templates_list_item_instances"."template_kind") AS slots, "templates_list_item_instances"."render_duration", "templates_list_item_instances"."last_rendered_at" FROM "templates_list_item_instances" INNER JOIN "layouts_list_item_instances" ON "layouts_list_item_instances"."id" = "templates_list_item_instances"."layout_instance_id" INNER JOIN "templates_list_item_definitions" ON "templates_list_item_definitions"."id" = "templates_list_item_instances"."template_definition_id"
            UNION ALL
            SELECT "templates_blurb_instances"."id" AS template_instance_id, 'Templates::BlurbInstance' AS template_instance_type, "templates_blurb_instances"."template_definition_id", 'Templates::BlurbDefinition' AS template_definition_type, "templates_blurb_instances"."layout_instance_id", 'Layouts::MainInstance' AS layout_instance_type, "layouts_main_instances"."layout_definition_id", 'Layouts::MainDefinition' AS layout_definition_type, "templates_blurb_instances"."entity_id", "templates_blurb_instances"."entity_type", "templates_blurb_instances"."position", "templates_blurb_instances"."layout_kind", "templates_blurb_instances"."template_kind", "templates_blurb_definitions"."width" AS width, "templates_blurb_instances"."generation", "templates_blurb_instances"."config", "templates_blurb_instances"."slots" || jsonb_build_object('template_kind', "templates_blurb_instances"."template_kind") AS slots, "templates_blurb_instances"."render_duration", "templates_blurb_instances"."last_rendered_at" FROM "templates_blurb_instances" INNER JOIN "layouts_main_instances" ON "layouts_main_instances"."id" = "templates_blurb_instances"."layout_instance_id" INNER JOIN "templates_blurb_definitions" ON "templates_blurb_definitions"."id" = "templates_blurb_instances"."template_definition_id"
            UNION ALL
            SELECT "templates_detail_instances"."id" AS template_instance_id, 'Templates::DetailInstance' AS template_instance_type, "templates_detail_instances"."template_definition_id", 'Templates::DetailDefinition' AS template_definition_type, "templates_detail_instances"."layout_instance_id", 'Layouts::MainInstance' AS layout_instance_type, "layouts_main_instances"."layout_definition_id", 'Layouts::MainDefinition' AS layout_definition_type, "templates_detail_instances"."entity_id", "templates_detail_instances"."entity_type", "templates_detail_instances"."position", "templates_detail_instances"."layout_kind", "templates_detail_instances"."template_kind", "templates_detail_definitions"."width" AS width, "templates_detail_instances"."generation", "templates_detail_instances"."config", "templates_detail_instances"."slots" || jsonb_build_object('template_kind', "templates_detail_instances"."template_kind") AS slots, "templates_detail_instances"."render_duration", "templates_detail_instances"."last_rendered_at" FROM "templates_detail_instances" INNER JOIN "layouts_main_instances" ON "layouts_main_instances"."id" = "templates_detail_instances"."layout_instance_id" INNER JOIN "templates_detail_definitions" ON "templates_detail_definitions"."id" = "templates_detail_instances"."template_definition_id"
            UNION ALL
            SELECT "templates_descendant_list_instances"."id" AS template_instance_id, 'Templates::DescendantListInstance' AS template_instance_type, "templates_descendant_list_instances"."template_definition_id", 'Templates::DescendantListDefinition' AS template_definition_type, "templates_descendant_list_instances"."layout_instance_id", 'Layouts::MainInstance' AS layout_instance_type, "layouts_main_instances"."layout_definition_id", 'Layouts::MainDefinition' AS layout_definition_type, "templates_descendant_list_instances"."entity_id", "templates_descendant_list_instances"."entity_type", "templates_descendant_list_instances"."position", "templates_descendant_list_instances"."layout_kind", "templates_descendant_list_instances"."template_kind", "templates_descendant_list_definitions"."width" AS width, "templates_descendant_list_instances"."generation", "templates_descendant_list_instances"."config", "templates_descendant_list_instances"."slots" || jsonb_build_object('template_kind', "templates_descendant_list_instances"."template_kind") AS slots, "templates_descendant_list_instances"."render_duration", "templates_descendant_list_instances"."last_rendered_at" FROM "templates_descendant_list_instances" INNER JOIN "layouts_main_instances" ON "layouts_main_instances"."id" = "templates_descendant_list_instances"."layout_instance_id" INNER JOIN "templates_descendant_list_definitions" ON "templates_descendant_list_definitions"."id" = "templates_descendant_list_instances"."template_definition_id"
            UNION ALL
            SELECT "templates_link_list_instances"."id" AS template_instance_id, 'Templates::LinkListInstance' AS template_instance_type, "templates_link_list_instances"."template_definition_id", 'Templates::LinkListDefinition' AS template_definition_type, "templates_link_list_instances"."layout_instance_id", 'Layouts::MainInstance' AS layout_instance_type, "layouts_main_instances"."layout_definition_id", 'Layouts::MainDefinition' AS layout_definition_type, "templates_link_list_instances"."entity_id", "templates_link_list_instances"."entity_type", "templates_link_list_instances"."position", "templates_link_list_instances"."layout_kind", "templates_link_list_instances"."template_kind", "templates_link_list_definitions"."width" AS width, "templates_link_list_instances"."generation", "templates_link_list_instances"."config", "templates_link_list_instances"."slots" || jsonb_build_object('template_kind', "templates_link_list_instances"."template_kind") AS slots, "templates_link_list_instances"."render_duration", "templates_link_list_instances"."last_rendered_at" FROM "templates_link_list_instances" INNER JOIN "layouts_main_instances" ON "layouts_main_instances"."id" = "templates_link_list_instances"."layout_instance_id" INNER JOIN "templates_link_list_definitions" ON "templates_link_list_definitions"."id" = "templates_link_list_instances"."template_definition_id"
            UNION ALL
            SELECT "templates_page_list_instances"."id" AS template_instance_id, 'Templates::PageListInstance' AS template_instance_type, "templates_page_list_instances"."template_definition_id", 'Templates::PageListDefinition' AS template_definition_type, "templates_page_list_instances"."layout_instance_id", 'Layouts::MainInstance' AS layout_instance_type, "layouts_main_instances"."layout_definition_id", 'Layouts::MainDefinition' AS layout_definition_type, "templates_page_list_instances"."entity_id", "templates_page_list_instances"."entity_type", "templates_page_list_instances"."position", "templates_page_list_instances"."layout_kind", "templates_page_list_instances"."template_kind", "templates_page_list_definitions"."width" AS width, "templates_page_list_instances"."generation", "templates_page_list_instances"."config", "templates_page_list_instances"."slots" || jsonb_build_object('template_kind', "templates_page_list_instances"."template_kind") AS slots, "templates_page_list_instances"."render_duration", "templates_page_list_instances"."last_rendered_at" FROM "templates_page_list_instances" INNER JOIN "layouts_main_instances" ON "layouts_main_instances"."id" = "templates_page_list_instances"."layout_instance_id" INNER JOIN "templates_page_list_definitions" ON "templates_page_list_definitions"."id" = "templates_page_list_instances"."template_definition_id"
            UNION ALL
            SELECT "templates_contributor_list_instances"."id" AS template_instance_id, 'Templates::ContributorListInstance' AS template_instance_type, "templates_contributor_list_instances"."template_definition_id", 'Templates::ContributorListDefinition' AS template_definition_type, "templates_contributor_list_instances"."layout_instance_id", 'Layouts::MainInstance' AS layout_instance_type, "layouts_main_instances"."layout_definition_id", 'Layouts::MainDefinition' AS layout_definition_type, "templates_contributor_list_instances"."entity_id", "templates_contributor_list_instances"."entity_type", "templates_contributor_list_instances"."position", "templates_contributor_list_instances"."layout_kind", "templates_contributor_list_instances"."template_kind", "templates_contributor_list_definitions"."width" AS width, "templates_contributor_list_instances"."generation", "templates_contributor_list_instances"."config", "templates_contributor_list_instances"."slots" || jsonb_build_object('template_kind', "templates_contributor_list_instances"."template_kind") AS slots, "templates_contributor_list_instances"."render_duration", "templates_contributor_list_instances"."last_rendered_at" FROM "templates_contributor_list_instances" INNER JOIN "layouts_main_instances" ON "layouts_main_instances"."id" = "templates_contributor_list_instances"."layout_instance_id" INNER JOIN "templates_contributor_list_definitions" ON "templates_contributor_list_definitions"."id" = "templates_contributor_list_instances"."template_definition_id"
            UNION ALL
            SELECT "templates_ordering_instances"."id" AS template_instance_id, 'Templates::OrderingInstance' AS template_instance_type, "templates_ordering_instances"."template_definition_id", 'Templates::OrderingDefinition' AS template_definition_type, "templates_ordering_instances"."layout_instance_id", 'Layouts::MainInstance' AS layout_instance_type, "layouts_main_instances"."layout_definition_id", 'Layouts::MainDefinition' AS layout_definition_type, "templates_ordering_instances"."entity_id", "templates_ordering_instances"."entity_type", "templates_ordering_instances"."position", "templates_ordering_instances"."layout_kind", "templates_ordering_instances"."template_kind", "templates_ordering_definitions"."width" AS width, "templates_ordering_instances"."generation", "templates_ordering_instances"."config", "templates_ordering_instances"."slots" || jsonb_build_object('template_kind', "templates_ordering_instances"."template_kind") AS slots, "templates_ordering_instances"."render_duration", "templates_ordering_instances"."last_rendered_at" FROM "templates_ordering_instances" INNER JOIN "layouts_main_instances" ON "layouts_main_instances"."id" = "templates_ordering_instances"."layout_instance_id" INNER JOIN "templates_ordering_definitions" ON "templates_ordering_definitions"."id" = "templates_ordering_instances"."template_definition_id"
            UNION ALL
            SELECT "templates_navigation_instances"."id" AS template_instance_id, 'Templates::NavigationInstance' AS template_instance_type, "templates_navigation_instances"."template_definition_id", 'Templates::NavigationDefinition' AS template_definition_type, "templates_navigation_instances"."layout_instance_id", 'Layouts::NavigationInstance' AS layout_instance_type, "layouts_navigation_instances"."layout_definition_id", 'Layouts::NavigationDefinition' AS layout_definition_type, "templates_navigation_instances"."entity_id", "templates_navigation_instances"."entity_type", "templates_navigation_instances"."position", "templates_navigation_instances"."layout_kind", "templates_navigation_instances"."template_kind", CAST(NULL AS template_width) AS width, "templates_navigation_instances"."generation", "templates_navigation_instances"."config", "templates_navigation_instances"."slots" || jsonb_build_object('template_kind', "templates_navigation_instances"."template_kind") AS slots, "templates_navigation_instances"."render_duration", "templates_navigation_instances"."last_rendered_at" FROM "templates_navigation_instances" INNER JOIN "layouts_navigation_instances" ON "layouts_navigation_instances"."id" = "templates_navigation_instances"."layout_instance_id" INNER JOIN "templates_navigation_definitions" ON "templates_navigation_definitions"."id" = "templates_navigation_instances"."template_definition_id"
            UNION ALL
            SELECT "templates_metadata_instances"."id" AS template_instance_id, 'Templates::MetadataInstance' AS template_instance_type, "templates_metadata_instances"."template_definition_id", 'Templates::MetadataDefinition' AS template_definition_type, "templates_metadata_instances"."layout_instance_id", 'Layouts::MetadataInstance' AS layout_instance_type, "layouts_metadata_instances"."layout_definition_id", 'Layouts::MetadataDefinition' AS layout_definition_type, "templates_metadata_instances"."entity_id", "templates_metadata_instances"."entity_type", "templates_metadata_instances"."position", "templates_metadata_instances"."layout_kind", "templates_metadata_instances"."template_kind", CAST(NULL AS template_width) AS width, "templates_metadata_instances"."generation", "templates_metadata_instances"."config", "templates_metadata_instances"."slots" || jsonb_build_object('template_kind', "templates_metadata_instances"."template_kind") AS slots, "templates_metadata_instances"."render_duration", "templates_metadata_instances"."last_rendered_at" FROM "templates_metadata_instances" INNER JOIN "layouts_metadata_instances" ON "layouts_metadata_instances"."id" = "templates_metadata_instances"."layout_instance_id" INNER JOIN "templates_metadata_definitions" ON "templates_metadata_definitions"."id" = "templates_metadata_instances"."template_definition_id"
            UNION ALL
            SELECT "templates_supplementary_instances"."id" AS template_instance_id, 'Templates::SupplementaryInstance' AS template_instance_type, "templates_supplementary_instances"."template_definition_id", 'Templates::SupplementaryDefinition' AS template_definition_type, "templates_supplementary_instances"."layout_instance_id", 'Layouts::SupplementaryInstance' AS layout_instance_type, "layouts_supplementary_instances"."layout_definition_id", 'Layouts::SupplementaryDefinition' AS layout_definition_type, "templates_supplementary_instances"."entity_id", "templates_supplementary_instances"."entity_type", "templates_supplementary_instances"."position", "templates_supplementary_instances"."layout_kind", "templates_supplementary_instances"."template_kind", CAST(NULL AS template_width) AS width, "templates_supplementary_instances"."generation", "templates_supplementary_instances"."config", "templates_supplementary_instances"."slots" || jsonb_build_object('template_kind', "templates_supplementary_instances"."template_kind") AS slots, "templates_supplementary_instances"."render_duration", "templates_supplementary_instances"."last_rendered_at" FROM "templates_supplementary_instances" INNER JOIN "layouts_supplementary_instances" ON "layouts_supplementary_instances"."id" = "templates_supplementary_instances"."layout_instance_id" INNER JOIN "templates_supplementary_definitions" ON "templates_supplementary_definitions"."id" = "templates_supplementary_instances"."template_definition_id"
          )
          INSERT INTO "templates_instance_digests"("template_instance_id", "template_instance_type", "template_definition_id", "template_definition_type", "layout_instance_id", "layout_instance_type", "layout_definition_id", "layout_definition_type", "entity_id", "entity_type", "position", "layout_kind", "template_kind", "width", "generation", "config", "slots", "last_rendered_at", "render_duration")
          SELECT "template_instance_id", "template_instance_type", "template_definition_id", "template_definition_type", "layout_instance_id", "layout_instance_type", "layout_definition_id", "layout_definition_type", "entity_id", "entity_type", "position", "layout_kind", "template_kind", "width", "generation", "config", "slots", "last_rendered_at", "render_duration" FROM digested_template_instances
          ON CONFLICT (template_instance_id, template_instance_type) DO UPDATE SET
            "template_definition_id" = EXCLUDED."template_definition_id",
            "template_definition_type" = EXCLUDED."template_definition_type",
            "layout_instance_id" = EXCLUDED."layout_instance_id",
            "layout_instance_type" = EXCLUDED."layout_instance_type",
            "layout_definition_id" = EXCLUDED."layout_definition_id",
            "layout_definition_type" = EXCLUDED."layout_definition_type",
            "entity_id" = EXCLUDED."entity_id",
            "entity_type" = EXCLUDED."entity_type",
            "position" = EXCLUDED."position",
            "layout_kind" = EXCLUDED."layout_kind",
            "template_kind" = EXCLUDED."template_kind",
            "width" = EXCLUDED."width",
            "generation" = EXCLUDED."generation",
            "config" = EXCLUDED."config",
            "slots" = EXCLUDED."slots",
            "last_rendered_at" = EXCLUDED."last_rendered_at",
            "render_duration" = EXCLUDED."render_duration",
            updated_at = CURRENT_TIMESTAMP
          SQL
        end
      end
    end
  end
end
